### ISSUE TITLE
Weird EOFError When Validating - pls help

### ISSUE THREAD

**Issue by MrPeterss** [MineDojo/MineDojo#100]
Hey,

I'm getting this really weird error. I originally got that malmo error that requires to replace the envirnoment from https://github.com/Microsoft/malmo/releases. I am running the ubuntu app on windows with python 3.9. I replaced the malmo provided by this repo with the newest release "Malmo-0.37.0-Linux-Ubuntu-18.04-64bit_withBoost_Python3.6" in the microsoft repo. Originally, I was getting a permission error, so i used chmod to give everyone access to the folder/files. now im getting this error. Anyone know what is going on?

Thanks in advance!

```
/home/pbid/.local/lib/python3.9/site-packages/numpy/core/numeric.py:330: RuntimeWarning: invalid value encountered in cast
  multiarray.copyto(a, fill_value, casting='unsafe')
/home/pbid/.local/lib/python3.9/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(
[INFO] Create a task with prompt: combat a spider in night plains with a diamond sword, shield, and a full suite of leather armors
[INFO:minedojo.tasks] Loaded 1581 Programmatic tasks, 1560 Creative tasks, and 1 special task: "Playthrough". Totally 3142 tasks loaded.
Traceback (most recent call last):
  File "/home/pbid/MineDojo/scripts/validate_install.py", line 14, in <module>
    env.reset()
  File "/home/pbid/.local/lib/python3.9/site-packages/gym/core.py", line 292, in reset
    return self.env.reset(**kwargs)
  File "/home/pbid/MineDojo/minedojo/sim/wrappers/ar_nn/delta_inventory_wrapper.py", line 78, in reset
    observation = self.env.reset(**kwargs)
  File "/home/pbid/.local/lib/python3.9/site-packages/gym/core.py", line 319, in reset
    observation = self.env.reset(**kwargs)
  File "/home/pbid/MineDojo/minedojo/sim/wrappers/ar_nn/nn_action_space_wrapper.py", line 259, in reset
    obs = self.env.reset(**kwargs)
  File "/home/pbid/MineDojo/minedojo/tasks/meta/base.py", line 87, in reset
    obs = self.env.reset()
  File "/home/pbid/MineDojo/minedojo/sim/wrappers/fast_reset.py", line 71, in reset
    return self.env.reset()
  File "/home/pbid/MineDojo/minedojo/sim/sim.py", line 419, in reset
    raw_obs = self._bridge_env.reset(episode_id, [xml])[0]
  File "/home/pbid/MineDojo/minedojo/sim/bridge/bridge_env/bridge_env.py", line 72, in reset
    self._setup_instances()
  File "/home/pbid/MineDojo/minedojo/sim/bridge/bridge_env/bridge_env.py", line 157, in _setup_instances
    self._instances.extend([f.result() for f in instance_futures])
  File "/home/pbid/MineDojo/minedojo/sim/bridge/bridge_env/bridge_env.py", line 157, in <listcomp>
    self._instances.extend([f.result() for f in instance_futures])
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pbid/MineDojo/minedojo/sim/bridge/bridge_env/bridge_env.py", line 177, in _get_new_instance
    instance.launch(replaceable=self._is_fault_tolerant)
  File "/home/pbid/MineDojo/minedojo/sim/bridge/mc_instance/instance.py", line 201, in launch
    raise EOFError(
EOFError: usage: /tmp/tmp9lyyxbf7/Minecraft/launchClient.sh [-replaceable] [-port 10000] [-scorepolicy 0123] [-env]
```

**Comment by MrPeterss** [comment]
I think I figured it out. The new Malmo doesn't allow any options that are run in minedojo\sim\bridge\mc_instance\instance.py, besides -port and -env... I got passed the error by removing the extra options (seed, rundir, etc) that are added to the array representing the command. I understand this is def not a fix, but does someone know what version of malmo is optimal for this?

**Comment by MrPeterss** [comment]
I'm guessing my little hacky fix didn't work, because I can't get anything to come up it just sits on "Loaded 1581" for hours. Have actually left it on for 2 hours now and nothing coming up

**Comment by YXHXianYu** [comment]
Same problem, I don't know how to figure it out.

**Comment by YXHXianYu** [comment]
> I think I figured it out. The new Malmo doesn't allow any options that are run in minedojo\sim\bridge\mc_instance\instance.py, besides -port and -env... I got passed the error by removing the extra options (seed, rundir, etc) that are added to the array representing the command. I understand this is def not a fix, but does someone know what version of malmo is optimal for this?

This may be useful.

From:
```python
        cmd = [launch_script, "-port", str(port), "-env", "-runDir", rundir]
        if self._seed:
            cmd += ["-seed", str(self._seed)]

        # add jdwp port if any set
        if self.jdwp_port:
            cmd += ["-jvm_debug_port", str(self.jdwp_port)]
```
To:
```python
        cmd = [launch_script, "-port", str(port), "-env"]
        #cmd = [launch_script, "-port", str(port), "-env", "-runDir", rundir]
        #if self._seed:
        #    cmd += ["-seed", str(self._seed)]

        # add jdwp port if any set
        #if self.jdwp_port:
        #    cmd += ["-jvm_debug_port", str(self.jdwp_port)]
```

EOFError is disappeared and you can see the Minecraft window.

However, a new exception comes out:

```
[INFO:minedojo.tasks] Loaded 1581 Programmatic tasks, 1560 Creative tasks, and 1 special task: "Playthrough". Totally 3142 tasks loaded.
Traceback (most recent call last):
  File "/home/yxh_xianyu/MineDojo/scripts/validate_install.py", line 14, in <module>
    env.reset()
  File "/home/yxh_xianyu/anaconda3/envs/minedojo/lib/python3.9/site-packages/gym/core.py", line 292, in reset
    return self.env.reset(**kwargs)
  File "/home/yxh_xianyu/MineDojo/minedojo/sim/wrappers/ar_nn/delta_inventory_wrapper.py", line 78, in reset
    observation = self.env.reset(**kwargs)
  File "/home/yxh_xianyu/anaconda3/envs/minedojo/lib/python3.9/site-packages/gym/core.py", line 319, in reset
    observation = self.env.reset(**kwargs)
  File "/home/yxh_xianyu/MineDojo/minedojo/sim/wrappers/ar_nn/nn_action_space_wrapper.py", line 259, in reset
    obs = self.env.reset(**kwargs)
  File "/home/yxh_xianyu/MineDojo/minedojo/tasks/meta/base.py", line 87, in reset
    obs = self.env.reset()
  File "/home/yxh_xianyu/MineDojo/minedojo/sim/wrappers/fast_reset.py", line 71, in reset
    return self.env.reset()
  File "/home/yxh_xianyu/MineDojo/minedojo/sim/sim.py", line 419, in reset
    raw_obs = self._bridge_env.reset(episode_id, [xml])[0]
  File "/home/yxh_xianyu/MineDojo/minedojo/sim/bridge/bridge_env/bridge_env.py", line 78, in reset
    self._send_mission(
  File "/home/yxh_xianyu/MineDojo/minedojo/sim/bridge/bridge_env/bridge_env.py", line 258, in _send_mission
    (ok,) = struct.unpack("!I", reply)
struct.error: unpack requires a buffer of 4 bytes
```

figuring....

**Comment by YXHXianYu** [comment]
#87

**Comment by YXHXianYu** [comment]
#87

**Comment by air-balls** [comment]
@YXHXianYu hello,have you solve the "Deprecated Gradle features"&"Minecraft process finished unexpectedly. There was an error with Malmo." problem? I replaced the Malmo version but it didn't work.Thanks in advance

**Comment by YXHXianYu** [comment]
> @YXHXianYu hello,have you solve the "Deprecated Gradle features"&"Minecraft process finished unexpectedly. There was an error with Malmo." problem? I replaced the Malmo version but it didn't work.Thanks in advance

You can refer to this [PR](https://github.com/MineDojo/MineDojo/pull/105).
The author create [a fork version](https://github.com/thomashopkins32/MineDojo).
I use the fork version and it works properly.
