### ISSUE TITLE
When running validate_install.py EOFError after fixing Malmo

### ISSUE THREAD

**Issue by Gnomecromancer** [MineDojo/MineDojo#114]
I got the Malmo error for which the fix is installing a new version of Malmo and now I'm getting this error message

EOFError: usage: /var/folders/k3/4jqff4zj3l585qb55mrc2lp00000gn/T/tmppi3m2d52/Minecraft/launchClient.sh [-replaceable] [-port 10000] [-scorepolicy 0123] [-env]

Full Result of validate_install.py after fixing Malmo:
[INFO:minedojo.tasks] Loaded 1581 Programmatic tasks, 1560 Creative tasks, and 1 special task: "Playthrough". Totally 3142 tasks loaded.
/Users/eliwolfe/miniconda3/envs/minedojo/lib/python3.9/site-packages/numpy/core/numeric.py:330: RuntimeWarning: invalid value encountered in cast
  multiarray.copyto(a, fill_value, casting='unsafe')
/Users/eliwolfe/miniconda3/envs/minedojo/lib/python3.9/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(
[INFO] Create a task with prompt: combat a spider in night plains with a diamond sword, shield, and a full suite of leather armors
[INFO:minedojo.tasks] Loaded 1581 Programmatic tasks, 1560 Creative tasks, and 1 special task: "Playthrough". Totally 3142 tasks loaded.
Traceback (most recent call last):
  File "/Users/eliwolfe/MineDojo/scripts/validate_install.py", line 14, in <module>
    env.reset()
  File "/Users/eliwolfe/miniconda3/envs/minedojo/lib/python3.9/site-packages/gym/core.py", line 292, in reset
    return self.env.reset(**kwargs)
  File "/Users/eliwolfe/MineDojo/minedojo/sim/wrappers/ar_nn/delta_inventory_wrapper.py", line 78, in reset
    observation = self.env.reset(**kwargs)
  File "/Users/eliwolfe/miniconda3/envs/minedojo/lib/python3.9/site-packages/gym/core.py", line 319, in reset
    observation = self.env.reset(**kwargs)
  File "/Users/eliwolfe/MineDojo/minedojo/sim/wrappers/ar_nn/nn_action_space_wrapper.py", line 259, in reset
    obs = self.env.reset(**kwargs)
  File "/Users/eliwolfe/MineDojo/minedojo/tasks/meta/base.py", line 87, in reset
    obs = self.env.reset()
  File "/Users/eliwolfe/MineDojo/minedojo/sim/wrappers/fast_reset.py", line 71, in reset
    return self.env.reset()
  File "/Users/eliwolfe/MineDojo/minedojo/sim/sim.py", line 419, in reset
    raw_obs = self._bridge_env.reset(episode_id, [xml])[0]
  File "/Users/eliwolfe/MineDojo/minedojo/sim/bridge/bridge_env/bridge_env.py", line 72, in reset
    self._setup_instances()
  File "/Users/eliwolfe/MineDojo/minedojo/sim/bridge/bridge_env/bridge_env.py", line 157, in _setup_instances
    self._instances.extend([f.result() for f in instance_futures])
  File "/Users/eliwolfe/MineDojo/minedojo/sim/bridge/bridge_env/bridge_env.py", line 157, in <listcomp>
    self._instances.extend([f.result() for f in instance_futures])
  File "/Users/eliwolfe/miniconda3/envs/minedojo/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Users/eliwolfe/miniconda3/envs/minedojo/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/Users/eliwolfe/miniconda3/envs/minedojo/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/eliwolfe/MineDojo/minedojo/sim/bridge/bridge_env/bridge_env.py", line 177, in _get_new_instance
    instance.launch(replaceable=self._is_fault_tolerant)
  File "/Users/eliwolfe/MineDojo/minedojo/sim/bridge/mc_instance/instance.py", line 201, in launch
    raise EOFError(
EOFError: usage: /var/folders/k3/4jqff4zj3l585qb55mrc2lp00000gn/T/tmppi3m2d52/Minecraft/launchClient.sh [-replaceable] [-port 10000] [-scorepolicy 0123] [-env]

**Comment by a1wj1** [comment]
Have you solved it? I have the same problem
