### ISSUE TITLE
Dosen't see Minecraft window pop up

### ISSUE THREAD

**Issue by bullhsu** [MineDojo/MineDojo#122]
Installation Success, but dosen't see any Minecraft window pop up. How can I fix it?
<img width="853" alt="螢幕擷取畫面 2024-03-19 112859" src="https://github.com/MineDojo/MineDojo/assets/156338299/7959b81f-2c4b-43b2-9836-bed97d0d022e">

**Comment by lyh1028** [comment]
I have the same problem. And running the example code
```
import minedojo

env = minedojo.make(
    task_id="harvest_wool_with_shears_and_sheep",
    image_size=(160, 256)
)
obs = env.reset()
for i in range(50):
    act = env.action_space.no_op()
    act[0] = 1    # forward/backward
    if i % 10 == 0:
        act[2] = 1    # jump
    obs, reward, done, info = env.step(act)
env.close()
```
causes error below:
[INFO:minedojo.tasks] Loaded 1581 Programmatic tasks, 1560 Creative tasks, and 1 special task: "Playthrough". Totally 3142 tasks loaded.
Traceback (most recent call last):
  File "/home/user/testdojo.py", line 7, in <module>
    obs = env.reset()
  File "/opt/conda/lib/python3.9/site-packages/gym/core.py", line 292, in reset
    return self.env.reset(**kwargs)
  File "/home/user/MineDojo/minedojo/sim/wrappers/ar_nn/delta_inventory_wrapper.py", line 78, in reset
    observation = self.env.reset(**kwargs)
  File "/opt/conda/lib/python3.9/site-packages/gym/core.py", line 319, in reset
    observation = self.env.reset(**kwargs)
  File "/home/user/MineDojo/minedojo/sim/wrappers/ar_nn/nn_action_space_wrapper.py", line 259, in reset
    obs = self.env.reset(**kwargs)
  File "/home/user/MineDojo/minedojo/tasks/meta/base.py", line 87, in reset
    obs = self.env.reset()
  File "/home/user/MineDojo/minedojo/sim/wrappers/fast_reset.py", line 71, in reset
    return self.env.reset()
  File "/home/user/MineDojo/minedojo/sim/sim.py", line 419, in reset
    raw_obs = self._bridge_env.reset(episode_id, [xml])[0]
  File "/home/user/MineDojo/minedojo/sim/bridge/bridge_env/bridge_env.py", line 84, in reset
    return self._query_first_obs()
  File "/home/user/MineDojo/minedojo/sim/bridge/bridge_env/bridge_env.py", line 191, in _query_first_obs
    info = instance.client_socket_recv_message().decode("utf-8")
AttributeError: 'NoneType' object has no attribute 'decode'

**Comment by Aurora-1412** [comment]
> Installation Success, but dosen't see any Minecraft window pop up. How can I fix it? <img alt="螢幕擷取畫面 2024-03-19 112859" width="853" src="https://private-user-images.githubusercontent.com/156338299/313904742-7959b81f-2c4b-43b2-9836-bed97d0d022e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDk5MTEsIm5iZiI6MTcxMTUwOTYxMSwicGF0aCI6Ii8xNTYzMzgyOTkvMzEzOTA0NzQyLTc5NTliODFmLTJjNGItNDNiMi05ODM2LWJlZDk3ZDBkMDIyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QwMzIwMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZjQ1OGZiNGM0YmQ3MmYzMzdjZmFhZmFiNmVjZTg5NDc3N2VlOTQzOGY4NGRkMzg3Y2EwMGI2ZGQwNDJiY2UxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sNi0Q3mofFhp4DSX13JHEYI3T9gJ3quUOyegz6nPaww">

you should first configure some service such as X11, and then configure $DISPLAY like: export DISPLAY=host.docker.internal:0.0 
You can search for specific tutorials on Google such as "Run GUI app in linux docker container on windows host"
