### ISSUE TITLE
MineDojo error Running

### ISSUE THREAD

**Issue by Max6468** [MineDojo/MineDojo#128]
max6468@max6468-MacBookPro:~/Escritorio$ vglrun python3 ia.py
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
/home/max6468/.local/lib/python3.10/site-packages/numpy/core/numeric.py:330: RuntimeWarning: invalid value encountered in cast
  multiarray.copyto(a, fill_value, casting='unsafe')
/home/max6468/.local/lib/python3.10/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
Traceback (most recent call last):
  File "/home/max6468/Escritorio/ia.py", line 7, in <module>
    obs = env.reset()
  File "/home/max6468/.local/lib/python3.10/site-packages/gym/core.py", line 292, in reset
    return self.env.reset(**kwargs)
  File "/home/max6468/.local/lib/python3.10/site-packages/minedojo/sim/wrappers/ar_nn/delta_inventory_wrapper.py", line 78, in reset
    observation = self.env.reset(**kwargs)
  File "/home/max6468/.local/lib/python3.10/site-packages/gym/core.py", line 319, in reset
    observation = self.env.reset(**kwargs)
  File "/home/max6468/.local/lib/python3.10/site-packages/minedojo/sim/wrappers/ar_nn/nn_action_space_wrapper.py", line 259, in reset
    obs = self.env.reset(**kwargs)
  File "/home/max6468/.local/lib/python3.10/site-packages/minedojo/tasks/meta/base.py", line 87, in reset
    obs = self.env.reset()
  File "/home/max6468/.local/lib/python3.10/site-packages/minedojo/sim/wrappers/fast_reset.py", line 71, in reset
    return self.env.reset()
  File "/home/max6468/.local/lib/python3.10/site-packages/minedojo/sim/sim.py", line 419, in reset
    raw_obs = self._bridge_env.reset(episode_id, [xml])[0]
  File "/home/max6468/.local/lib/python3.10/site-packages/minedojo/sim/bridge/bridge_env/bridge_env.py", line 72, in reset
    self._setup_instances()
  File "/home/max6468/.local/lib/python3.10/site-packages/minedojo/sim/bridge/bridge_env/bridge_env.py", line 157, in _setup_instances
    self._instances.extend([f.result() for f in instance_futures])
  File "/home/max6468/.local/lib/python3.10/site-packages/minedojo/sim/bridge/bridge_env/bridge_env.py", line 157, in <listcomp>
    self._instances.extend([f.result() for f in instance_futures])
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/max6468/.local/lib/python3.10/site-packages/minedojo/sim/bridge/bridge_env/bridge_env.py", line 177, in _get_new_instance
    instance.launch(replaceable=self._is_fault_tolerant)
  File "/home/max6468/.local/lib/python3.10/site-packages/minedojo/sim/bridge/mc_instance/instance.py", line 201, in launch
    raise EOFError(
EOFError: usage: /tmp/tmpafkhs468/Minecraft/launchClient.sh [-replaceable] [-port 10000] [-scorepolicy 0123] [-env]

Minecraft process finished unexpectedly. There was an error with Malmo.

**Comment by XiaoWei-i** [comment]
same error
