### ISSUE TITLE
Minecraft process finished unexpectedly. There was an error with Malmo.

### ISSUE THREAD

**Issue by AdyStudios** [MineDojo/MineDojo#14]
I'm getting Minecraft process finished unexpectedly. There was an error with Malmo. this error when trying to run validate_install.py, after building.
(Kali Linux in virtualbox)

**Comment by Martysh12** [comment]
I am having the same issue. Here's the log:
```
In [12]: obs = env.reset()
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
---------------------------------------------------------------------------
EOFError                                  Traceback (most recent call last)
<ipython-input-12-a57416bd8216> in <module>
----> 1 obs = env.reset()

~/.local/lib/python3.10/site-packages/gym/core.py in reset(self, **kwargs)
    290 
    291     def reset(self, **kwargs):
--> 292         return self.env.reset(**kwargs)
    293 
    294     def render(self, mode="human", **kwargs):

~/.local/lib/python3.10/site-packages/minedojo/sim/wrappers/ar_nn/delta_inventory_wrapper.py in reset(self, **kwargs)
     76 
     77     def reset(self, **kwargs):
---> 78         observation = self.env.reset(**kwargs)
     79         self._prev_inventory = deepcopy(observation["inventory"])
     80         self._prev_mask = deepcopy(observation["masks"]["craft_smelt"])

~/.local/lib/python3.10/site-packages/gym/core.py in reset(self, **kwargs)
    317 class ObservationWrapper(Wrapper):
    318     def reset(self, **kwargs):
--> 319         observation = self.env.reset(**kwargs)
    320         return self.observation(observation)
    321 

~/.local/lib/python3.10/site-packages/minedojo/sim/wrappers/ar_nn/nn_action_space_wrapper.py in reset(self, **kwargs)
    257 
    258     def reset(self, **kwargs):
--> 259         obs = self.env.reset(**kwargs)
    260         self._inventory_names = obs["inventory"]["name"].copy()
    261         return obs

~/.local/lib/python3.10/site-packages/minedojo/tasks/meta/playthrough.py in reset(self, **kwargs)
    169     def reset(self, **kwargs):
    170         self._elapsed_steps = 0
--> 171         return self.env.reset(**kwargs)
    172 
    173     def step(self, action):

~/.local/lib/python3.10/site-packages/minedojo/sim/wrappers/fast_reset.py in reset(self)
     69         if not self._server_start:
     70             self._server_start = True
---> 71             return self.env.reset()
     72         else:
     73             for cmd in self._reset_cmds:

~/.local/lib/python3.10/site-packages/minedojo/sim/sim.py in reset(self)
    417 
    418         xml = etree.fromstring(self._sim_spec.to_xml(episode_id))
--> 419         raw_obs = self._bridge_env.reset(episode_id, [xml])[0]
    420         obs, info = self._process_raw_obs(raw_obs)
    421         self._prev_obs, self._prev_info = deepcopy(obs), deepcopy(info)

~/.local/lib/python3.10/site-packages/minedojo/sim/bridge/bridge_env/bridge_env.py in reset(self, episode_uid, agent_xmls)
     70 
     71         # Start missing instances, quit episodes, and make socket connections
---> 72         self._setup_instances()
     73         self._terminated = False
     74 

~/.local/lib/python3.10/site-packages/minedojo/sim/bridge/bridge_env/bridge_env.py in _setup_instances(self)
    155                 for _ in range(n_instances_to_start):
    156                     instance_futures.append(tpe.submit(self._get_new_instance))
--> 157             self._instances.extend([f.result() for f in instance_futures])
    158 
    159         # establish socket connections

~/.local/lib/python3.10/site-packages/minedojo/sim/bridge/bridge_env/bridge_env.py in <listcomp>(.0)
    155                 for _ in range(n_instances_to_start):
    156                     instance_futures.append(tpe.submit(self._get_new_instance))
--> 157             self._instances.extend([f.result() for f in instance_futures])
    158 
    159         # establish socket connections

/usr/lib/python3.10/concurrent/futures/_base.py in result(self, timeout)
    437                     raise CancelledError()
    438                 elif self._state == FINISHED:
--> 439                     return self.__get_result()
    440 
    441                 self._condition.wait(timeout)

/usr/lib/python3.10/concurrent/futures/_base.py in __get_result(self)
    389         if self._exception:
    390             try:
--> 391                 raise self._exception
    392             finally:
    393                 # Break a reference cycle with the exception in self._exception

/usr/lib/python3.10/concurrent/futures/thread.py in run(self)
     56 
     57         try:
---> 58             result = self.fn(*self.args, **self.kwargs)
     59         except BaseException as exc:
     60             self.future.set_exception(exc)

~/.local/lib/python3.10/site-packages/minedojo/sim/bridge/bridge_env/bridge_env.py in _get_new_instance(self, port, instance_id)
    175             )
    176 
--> 177         instance.launch(replaceable=self._is_fault_tolerant)
    178         instance.had_to_clean = False
    179         return instance

~/.local/lib/python3.10/site-packages/minedojo/sim/bridge/mc_instance/instance.py in launch(self, daemonize, replaceable)
    199                         error_str += spline + "\n"
    200                     # Throw an exception!
--> 201                     raise EOFError(
    202                         error_str                                                                                                                                                     
    203                         + "\n\nMinecraft process finished unexpectedly. There was an error with Malmo."

EOFError: /tmp/tmpu7i4r9ix/Minecraft
# Configuration file
# Autogenerated from command-line options

malmoports {
  I:portOverride=9712
}
malmoscore {
  I:policy=0
}

malmoseed {
  I:seed=350528098
}

runtype {
  B:replaceable=true
}

envtype {
  B:env=true
}

/tmp/tmpu7i4r9ix/Minecraft/run

HELLO
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true

> Configure project :
This mapping 'snapshot_20161220' was designed for MC 1.11! Use at your own peril.
Found AccessTransformer: malmomod_at.cfg

> Task :deobfCompileDummyTask
> Task :deobfProvidedDummyTask
> Task :getVersionJson
> Task :extractUserdev
> Task :downloadClient SKIPPED
> Task :downloadServer SKIPPED
> Task :splitServerJar SKIPPED
> Task :mergeJars SKIPPED
> Task :applyBinaryPatches FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':applyBinaryPatches'.
> java/util/jar/Pack200

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':applyBinaryPatches'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.NoClassDefFoundError: java/util/jar/Pack200
        at net.minecraftforge.gradle.user.patcherUser.TaskApplyBinPatches.setup(TaskApplyBinPatches.java:202)
        at net.minecraftforge.gradle.user.patcherUser.TaskApplyBinPatches.doTask(TaskApplyBinPatches.java:80)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 31 more
Caused by: java.lang.ClassNotFoundException: java.util.jar.Pack200
        ... 50 more


* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5s
5 actionable tasks: 5 executed


Minecraft process finished unexpectedly. There was an error with Malmo.
```

**Comment by AdyStudios** [comment]
I reinstalled with ubuntu and solved it, so know it is obsolete

**Comment by yunfanjiang** [comment]
Hey @Martysh12 , your error seems to be relevant to Java version. Were you using Java JDK8?

**Comment by Sanokei** [comment]
![image](https://user-images.githubusercontent.com/36809574/182002792-0196fca3-804c-4cdc-8024-566a0216c2e4.png)
Getting the same error. Have the right JDK8 version

**Comment by yunfanjiang** [comment]
@Sanokei Thank you for your solution! Close this issue now.
