### ISSUE TITLE
Problem with ValueError: TODO

### ISSUE THREAD

**Issue by Gametron303** [MineDojo/MineDojo#24]
When I launch file validate_install.py on Windows 10 I get this traceback after some time. Version Python 3.10. Processor Ryzen 5 5600X.
 
```PS C:\Users\gamet\Downloads\MineDojo> python scripts\validate_install.py
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
C:\Users\gamet\AppData\Local\Programs\Python\Python310\lib\site-packages\gym\spaces\box.py:73: UserWarning: ←[33mWARN: Box bound precision lowered by casting to float32←[0m
  logger.warn(
[INFO] Create a task with prompt: combat a spider in night plains with a diamond sword, shield, and a full suite of leather armors
Traceback (most recent call last):
  File "C:\Users\gamet\Downloads\MineDojo\scripts\validate_install.py", line 14, in <module>
    env.reset()
  File "C:\Users\gamet\AppData\Local\Programs\Python\Python310\lib\site-packages\gym\core.py", line 292, in reset
    return self.env.reset(**kwargs)
  File "c:\users\gamet\downloads\minedojo\minedojo\sim\wrappers\ar_nn\delta_inventory_wrapper.py", line 78, in reset
    observation = self.env.reset(**kwargs)
  File "C:\Users\gamet\AppData\Local\Programs\Python\Python310\lib\site-packages\gym\core.py", line 319, in reset
    observation = self.env.reset(**kwargs)
  File "c:\users\gamet\downloads\minedojo\minedojo\sim\wrappers\ar_nn\nn_action_space_wrapper.py", line 259, in reset
    obs = self.env.reset(**kwargs)
  File "c:\users\gamet\downloads\minedojo\minedojo\tasks\meta\base.py", line 87, in reset
    obs = self.env.reset()
  File "c:\users\gamet\downloads\minedojo\minedojo\sim\wrappers\fast_reset.py", line 71, in reset
    return self.env.reset()
  File "c:\users\gamet\downloads\minedojo\minedojo\sim\sim.py", line 419, in reset
    raw_obs = self._bridge_env.reset(episode_id, [xml])[0]
  File "c:\users\gamet\downloads\minedojo\minedojo\sim\bridge\bridge_env\bridge_env.py", line 72, in reset
    self._setup_instances()
  File "c:\users\gamet\downloads\minedojo\minedojo\sim\bridge\bridge_env\bridge_env.py", line 157, in _setup_instances
    self._instances.extend([f.result() for f in instance_futures])
  File "c:\users\gamet\downloads\minedojo\minedojo\sim\bridge\bridge_env\bridge_env.py", line 157, in <listcomp>
    self._instances.extend([f.result() for f in instance_futures])
  File "C:\Users\gamet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\gamet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\gamet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\gamet\downloads\minedojo\minedojo\sim\bridge\bridge_env\bridge_env.py", line 177, in _get_new_instance
    instance.launch(replaceable=self._is_fault_tolerant)
  File "c:\users\gamet\downloads\minedojo\minedojo\sim\bridge\mc_instance\instance.py", line 161, in launch
    self.minecraft_process = self._launch_minecraft(
  File "c:\users\gamet\downloads\minedojo\minedojo\sim\bridge\mc_instance\instance.py", line 370, in _launch_minecraft
    raise ValueError("TODO")
ValueError: TODO```

**Comment by Sanokei** [comment]
Pretty sure it doesnt work in Windows 10 or Python 3.10... or both

I am also running on windows 10, I used wsl instead and it worked great. 
check this comment for more info
https://github.com/MineDojo/MineDojo/issues/22#issuecomment-1200431684

**Comment by yunfanjiang** [comment]
Hey @Gametron303 , please follow @Sanokei 's instruction to run on Windows. Thank you for your help again @Sanokei ! I'm closing this issue now.
