### ISSUE TITLE
Minecraft process finished unexpectedly. There was an error with Malmo.

### ISSUE THREAD

**Issue by yangboz** [MineDojo/MineDojo#46]
python3.9
idk openjdk version "1.8.0_342"

Gradle 7.6
------------------------------------------------------------

Build time:   2022-11-25 13:35:10 UTC
Revision:     daece9dbc5b79370cc8e4fd6fe4b2cd400e150a8

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_342 (Amazon.com Inc. 25.342-b07)
OS:           Mac OS X 12.5.1 aarch64

Setting gradle 7.6 as default.
(py39) yangboz@yangbozs-MBP minedojo % python test.py    
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
/opt/anaconda3/envs/py39/lib/python3.9/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
Traceback (most recent call last):
  File "/Users/yangboz/Documents/minedojo/test.py", line 7, in <module>
    obs = env.reset()
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/gym/core.py", line 292, in reset
    return self.env.reset(**kwargs)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/minedojo/sim/wrappers/ar_nn/delta_inventory_wrapper.py", line 78, in reset
    observation = self.env.reset(**kwargs)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/gym/core.py", line 319, in reset
    observation = self.env.reset(**kwargs)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/minedojo/sim/wrappers/ar_nn/nn_action_space_wrapper.py", line 259, in reset
    obs = self.env.reset(**kwargs)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/minedojo/tasks/meta/base.py", line 87, in reset
    obs = self.env.reset()
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/minedojo/sim/wrappers/fast_reset.py", line 71, in reset
    return self.env.reset()

**Comment by AndreaHsu** [comment]
Hi, @yangboz I also encounter this problem, did you fix it?

**Comment by yangboz** [comment]
> Hi, @yangboz I also encounter this problem, did you fix it?

not yet , still under diving , it seems JDK related issue on Gradle.  or others.

**Comment by LikeJulia** [comment]
Same errors

**Comment by ZiyiLiubird** [comment]
same errors

**Comment by ngundotra** [comment]
Try updating your JDK - for me, I was using the wrong version of gradle.

(ubuntu 18.04) I had to install latest version of `gradle` using `sdkman`, then I was able to run this validate correctly.

Hope that helps!
