### ISSUE TITLE
ConnectionRefused Error when trying to run validate_install.py

### ISSUE THREAD

**Issue by Z0zzz** [MineDojo/MineDojo#57]
[INFO:minedojo.tasks] Loaded 1581 Programmatic tasks, 1560 Creative tasks, and 1 special task: "Playthrough". Totally 3142 tasks loaded.
<__array_function__ internals>:200: RuntimeWarning: invalid value encountered in cast
/usr/local/anaconda3/envs/MineDojo/lib/python3.9/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(
[INFO] Create a task with prompt: combat a spider in night plains with a diamond sword, shield, and a full suite of leather armors
target port 11330
instance directory:  /var/folders/y7/dmw6mp6x7qz5hqc8qwpwwy1c0000gn/T/tmp60y5le75
Command:  ['/var/folders/y7/dmw6mp6x7qz5hqc8qwpwwy1c0000gn/T/tmp60y5le75/Minecraft/launchClient.sh']
[INFO:minedojo.tasks] Loaded 1581 Programmatic tasks, 1560 Creative tasks, and 1 special task: "Playthrough". Totally 3142 tasks loaded.
Failed to reset (socket error), trying again!
Cleaning connection! Something must have gone wrong.
Connection with Minecraft client Malmo[None:f0b2b7, proc=24072, addr=localhost:11330, locked=True] cleaned more than once; restarting.
Attempted to send kill command to minecraft process and failed with exception [Errno 61] Connection refused
Traceback (most recent call last):
  File "/Users/yoloz/MineDojo/scripts/validate_install.py", line 14, in <module>
    env.reset()
  File "/usr/local/anaconda3/envs/MineDojo/lib/python3.9/site-packages/gym/core.py", line 292, in reset
    return self.env.reset(**kwargs)
  File "/Users/yoloz/MineDojo/minedojo/sim/wrappers/ar_nn/delta_inventory_wrapper.py", line 78, in reset
    observation = self.env.reset(**kwargs)
  File "/usr/local/anaconda3/envs/MineDojo/lib/python3.9/site-packages/gym/core.py", line 319, in reset
    observation = self.env.reset(**kwargs)
  File "/Users/yoloz/MineDojo/minedojo/sim/wrappers/ar_nn/nn_action_space_wrapper.py", line 259, in reset
    obs = self.env.reset(**kwargs)
  File "/Users/yoloz/MineDojo/minedojo/tasks/meta/base.py", line 87, in reset
    obs = self.env.reset()
  File "/Users/yoloz/MineDojo/minedojo/sim/wrappers/fast_reset.py", line 71, in reset
    return self.env.reset()
  File "/Users/yoloz/MineDojo/minedojo/sim/sim.py", line 419, in reset
    raw_obs = self._bridge_env.reset(episode_id, [xml])[0]
  File "/Users/yoloz/MineDojo/minedojo/sim/bridge/bridge_env/bridge_env.py", line 72, in reset
    self._setup_instances()
  File "/Users/yoloz/MineDojo/minedojo/sim/bridge/bridge_env/bridge_env.py", line 162, in _setup_instances
    self._create_connection(instance)
  File "/Users/yoloz/MineDojo/minedojo/sim/bridge/utils/retry.py", line 29, in wrapper
    raise e
  File "/Users/yoloz/MineDojo/minedojo/sim/bridge/utils/retry.py", line 18, in wrapper
    return func(*args, **kwargs)
  File "/Users/yoloz/MineDojo/minedojo/sim/bridge/bridge_env/bridge_env.py", line 227, in _create_connection
    raise e
  File "/Users/yoloz/MineDojo/minedojo/sim/bridge/bridge_env/bridge_env.py", line 218, in _create_connection
    instance.create_instance_socket(socktime=self.SOCKTIME)
  File "/Users/yoloz/MineDojo/minedojo/sim/bridge/mc_instance/instance.py", line 111, in create_instance_socket
    sock.connect((self.host, self.port))
ConnectionRefusedError: [Errno 61] Connection refused

**Comment by Z0zzz** [comment]
I'm running locally on a macbook, and I have tried out prepending MINEDOJO_HEADLESS=1, doesn't seem to work.
