### ISSUE TITLE
Installing MineDojo on Windows 11 fails due to UnicodeDecodeError

### ISSUE THREAD

**Issue by julianertle** [MineDojo/MineDojo#71]
I noticed that running the command "pip install -e " on Windows leads to the following error:

```
-----------------------------------------------------------------------------------------------
C:\Users\Julian\Documents\Programme\MineDojo\MineDojo> pip install -e .
Obtaining file:///C:/Users/Julian/Documents/Programme/MineDojo/MineDojo
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Julian\Documents\Programme\MineDojo\MineDojo\setup.py", line 38, in <module>
          long_description=_read_file("README.md"),
        File "C:\Users\Julian\Documents\Programme\MineDojo\MineDojo\setup.py", line 16, in _read_file
          return fp.read()
        File "C:\Users\Julian\miniconda3\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 15627: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for `details.`

-----------------------------------------------------------------------------------------------
```
It seems to be a decoding error however I am not qualified enough to try to fix it myself.

However it is possible to provisionally avoid this error by commenting out one line in the setup.py file.
If you add the character "#" in front of the line `long_description=_read_file("README.md")` this error can be avoided and
the installation succeeds. 

```
...

setup(
    name=PKG_NAME,
    version=VERSION,
    author=f"MineDojo Team",
    url="http://github.com/MineDojo/MineDojo",
    description="research project",
    #long_description=_read_file("README.md"),
    long_description_content_type="text/markdown",
    keywords=["Deep Learning", "Machine Learning"],
    license="MIT License",
    packages=find_packages(include=f"{PKG_NAME}.*"),
    include_package_data=True,
    zip_safe=False,
    install_requires=_read_install_requires(),
    extras_require=_fill_extras(EXTRAS),
    python_requires=">=3.9",
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Environment :: Console",
        "Programming Language :: Python :: 3.9",
    ],
)
```
I hope someone can fix this problem :)

**Comment by julianertle** [comment]
Oh it might be also worth mentioning that I was not able to verify and finish the installation with `python minedojo/scripts/validate_install.py` since I encountered the following error: 

```
C:\Users\Julian\Documents\Programme\MineDojo> python minedojo/scripts/validate_install.py
[INFO:minedojo.tasks] Loaded 1581 Programmatic tasks, 1560 Creative tasks, and 1 special task: "Playthrough". Totally 3142 tasks loaded.
<__array_function__ internals>:200: RuntimeWarning: invalid value encountered in cast
C:\Users\Julian\miniconda3\lib\site-packages\gym\spaces\box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(
[INFO] Create a task with prompt: combat a spider in night plains with a diamond sword, shield, and a full suite of leather armors
Traceback (most recent call last):
  File "C:\Users\Julian\Documents\Programme\MineDojo\minedojo\scripts\validate_install.py", line 14, in <module>
    env.reset()
  File "C:\Users\Julian\miniconda3\lib\site-packages\gym\core.py", line 292, in reset
    return self.env.reset(**kwargs)
  File "c:\users\julian\documents\programme\minedojo\minedojo\minedojo\sim\wrappers\ar_nn\delta_inventory_wrapper.py", line 78, in reset
    observation = self.env.reset(**kwargs)
  File "C:\Users\Julian\miniconda3\lib\site-packages\gym\core.py", line 319, in reset
    observation = self.env.reset(**kwargs)
  File "c:\users\julian\documents\programme\minedojo\minedojo\minedojo\sim\wrappers\ar_nn\nn_action_space_wrapper.py", line 259, in reset
    obs = self.env.reset(**kwargs)
  File "c:\users\julian\documents\programme\minedojo\minedojo\minedojo\tasks\meta\base.py", line 87, in reset
    obs = self.env.reset()
  File "c:\users\julian\documents\programme\minedojo\minedojo\minedojo\sim\wrappers\fast_reset.py", line 71, in reset
    return self.env.reset()
  File "c:\users\julian\documents\programme\minedojo\minedojo\minedojo\sim\sim.py", line 419, in reset
    raw_obs = self._bridge_env.reset(episode_id, [xml])[0]
  File "c:\users\julian\documents\programme\minedojo\minedojo\minedojo\sim\bridge\bridge_env\bridge_env.py", line 72, in reset
    self._setup_instances()
  File "c:\users\julian\documents\programme\minedojo\minedojo\minedojo\sim\bridge\bridge_env\bridge_env.py", line 157, in _setup_instances
    self._instances.extend([f.result() for f in instance_futures])
  File "c:\users\julian\documents\programme\minedojo\minedojo\minedojo\sim\bridge\bridge_env\bridge_env.py", line 157, in <listcomp>
    self._instances.extend([f.result() for f in instance_futures])
  File "C:\Users\Julian\miniconda3\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Users\Julian\miniconda3\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\Julian\miniconda3\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\julian\documents\programme\minedojo\minedojo\minedojo\sim\bridge\bridge_env\bridge_env.py", line 177, in _get_new_instance
    instance.launch(replaceable=self._is_fault_tolerant)
  File "c:\users\julian\documents\programme\minedojo\minedojo\minedojo\sim\bridge\mc_instance\instance.py", line 161, in launch
    self.minecraft_process = self._launch_minecraft(
  File "c:\users\julian\documents\programme\minedojo\minedojo\minedojo\sim\bridge\mc_instance\instance.py", line 370, in _launch_minecraft
    raise ValueError("TODO")
ValueError: TODO
```
I think the issue here is simply because of incomplete or missing implementations in the code for Windows, which is not surprising considering that the direct installation of MineDojo was only tested on Ubuntu 20.04 and MacOS.

The error occurs in minedojo\sim\bridge\mc_instance\instance.py in the _launch_minecraft() method or line 370: 

```
...

if os.name == "nt":
            raise ValueError("TODO")

...
```
Anyone got any ideas on how to avoid this error?

**Comment by RizzyPR** [comment]
I am trying to install on Windows 11 using Conda as well, and I get this same error. To even get to this point I had to resort to an older version of pip. 

(minedojo) C:\Users\preit\Desktop\MineDojo\scripts>python validate_install.py
[INFO:minedojo.tasks] Loaded 1581 Programmatic tasks, 1560 Creative tasks, and 1 special task: "Playthrough". Totally 3142 tasks loaded.
C:\Users\preit\.conda\envs\minedojo\lib\site-packages\numpy\core\numeric.py:330: RuntimeWarning: invalid value encountered in cast
  multiarray.copyto(a, fill_value, casting='unsafe')
C:\Users\preit\.conda\envs\minedojo\lib\site-packages\gym\spaces\box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(
[INFO] Create a task with prompt: combat a spider in night plains with a diamond sword, shield, and a full suite of leather armors
Traceback (most recent call last):
  File "C:\Users\preit\Desktop\MineDojo\scripts\validate_install.py", line 14, in <module>
    env.reset()
  File "C:\Users\preit\.conda\envs\minedojo\lib\site-packages\gym\core.py", line 292, in reset
    return self.env.reset(**kwargs)
  File "c:\users\preit\desktop\minedojo\minedojo\sim\wrappers\ar_nn\delta_inventory_wrapper.py", line 78, in reset
    observation = self.env.reset(**kwargs)
  File "C:\Users\preit\.conda\envs\minedojo\lib\site-packages\gym\core.py", line 319, in reset
    observation = self.env.reset(**kwargs)
  File "c:\users\preit\desktop\minedojo\minedojo\sim\wrappers\ar_nn\nn_action_space_wrapper.py", line 259, in reset
    obs = self.env.reset(**kwargs)
  File "c:\users\preit\desktop\minedojo\minedojo\tasks\meta\base.py", line 87, in reset
    obs = self.env.reset()
  File "c:\users\preit\desktop\minedojo\minedojo\sim\wrappers\fast_reset.py", line 71, in reset
    return self.env.reset()
  File "c:\users\preit\desktop\minedojo\minedojo\sim\sim.py", line 419, in reset
    raw_obs = self._bridge_env.reset(episode_id, [xml])[0]
  File "c:\users\preit\desktop\minedojo\minedojo\sim\bridge\bridge_env\bridge_env.py", line 72, in reset
    self._setup_instances()
  File "c:\users\preit\desktop\minedojo\minedojo\sim\bridge\bridge_env\bridge_env.py", line 157, in _setup_instances
    self._instances.extend([f.result() for f in instance_futures])
  File "c:\users\preit\desktop\minedojo\minedojo\sim\bridge\bridge_env\bridge_env.py", line 157, in <listcomp>
    self._instances.extend([f.result() for f in instance_futures])
  File "C:\Users\preit\.conda\envs\minedojo\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\preit\.conda\envs\minedojo\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\preit\.conda\envs\minedojo\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\preit\desktop\minedojo\minedojo\sim\bridge\bridge_env\bridge_env.py", line 177, in _get_new_instance
    instance.launch(replaceable=self._is_fault_tolerant)
  File "c:\users\preit\desktop\minedojo\minedojo\sim\bridge\mc_instance\instance.py", line 161, in launch
    self.minecraft_process = self._launch_minecraft(
  File "c:\users\preit\desktop\minedojo\minedojo\sim\bridge\mc_instance\instance.py", line 370, in _launch_minecraft
    raise ValueError("TODO")
ValueError: TODO

bummer.
