### ISSUE TITLE
Error When Verifying 

### ISSUE THREAD

**Issue by Veitaserum4** [MineDojo/MineDojo#86]
I've looked at every issue, tried all the solutions i see there, but nothing fixes my problem. I'm using Linux Mint

(base) jacob@JacobMint:/mnt/cfebbf6f-6208-480d-be0e-bc78d603f59a/MineDojo$ xvfb-run python /mnt/cfebbf6f-6208-480d-be0e-bc78d603f59a/MineDojo/scripts/validate_install.py
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
<__array_function__ internals>:200: RuntimeWarning: invalid value encountered in cast
/home/jacob/anaconda3/lib/python3.9/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(
[INFO] Create a task with prompt: combat a spider in night plains with a diamond sword, shield, and a full suite of leather armors
[INFO:minedojo.tasks] Loaded 1581 Programmatic tasks, 1560 Creative tasks, and 1 special task: "Playthrough". Totally 3142 tasks loaded.
Traceback (most recent call last):
  File "/mnt/cfebbf6f-6208-480d-be0e-bc78d603f59a/MineDojo/scripts/validate_install.py", line 14, in <module>
    env.reset()
  File "/home/jacob/anaconda3/lib/python3.9/site-packages/gym/core.py", line 292, in reset
    return self.env.reset(**kwargs)
  File "/home/jacob/anaconda3/lib/python3.9/site-packages/minedojo/sim/wrappers/ar_nn/delta_inventory_wrapper.py", line 78, in reset
    observation = self.env.reset(**kwargs)
  File "/home/jacob/anaconda3/lib/python3.9/site-packages/gym/core.py", line 319, in reset
    observation = self.env.reset(**kwargs)
  File "/home/jacob/anaconda3/lib/python3.9/site-packages/minedojo/sim/wrappers/ar_nn/nn_action_space_wrapper.py", line 259, in reset
    obs = self.env.reset(**kwargs)
  File "/home/jacob/anaconda3/lib/python3.9/site-packages/minedojo/tasks/meta/base.py", line 87, in reset
    obs = self.env.reset()
  File "/home/jacob/anaconda3/lib/python3.9/site-packages/minedojo/sim/wrappers/fast_reset.py", line 71, in reset
    return self.env.reset()
  File "/home/jacob/anaconda3/lib/python3.9/site-packages/minedojo/sim/sim.py", line 419, in reset
    raw_obs = self._bridge_env.reset(episode_id, [xml])[0]
  File "/home/jacob/anaconda3/lib/python3.9/site-packages/minedojo/sim/bridge/bridge_env/bridge_env.py", line 72, in reset
    self._setup_instances()
  File "/home/jacob/anaconda3/lib/python3.9/site-packages/minedojo/sim/bridge/bridge_env/bridge_env.py", line 157, in _setup_instances
    self._instances.extend([f.result() for f in instance_futures])
  File "/home/jacob/anaconda3/lib/python3.9/site-packages/minedojo/sim/bridge/bridge_env/bridge_env.py", line 157, in <listcomp>
    self._instances.extend([f.result() for f in instance_futures])
  File "/home/jacob/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/jacob/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/jacob/anaconda3/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jacob/anaconda3/lib/python3.9/site-packages/minedojo/sim/bridge/bridge_env/bridge_env.py", line 177, in _get_new_instance
    instance.launch(replaceable=self._is_fault_tolerant)
  File "/home/jacob/anaconda3/lib/python3.9/site-packages/minedojo/sim/bridge/mc_instance/instance.py", line 201, in launch
    raise EOFError(
EOFError: /tmp/tmpvppmr74_/Minecraft
# Configuration file
# Autogenerated from command-line options

malmoports {
  I:portOverride=12353
}
malmoscore {
  I:policy=0
}

malmoseed {
  I:seed=37592391
}

runtype {
  B:replaceable=true
}

envtype {
  B:env=true
}

/tmp/tmpvppmr74_/Minecraft/run

HELLO

> Configure project :
This mapping 'snapshot_20161220' was designed for MC 1.11! Use at your own peril.
Found AccessTransformer: malmomod_at.cfg

> Task :deobfCompileDummyTask
> Task :deobfProvidedDummyTask
> Task :getVersionJson
> Task :extractUserdev
> Task :downloadClient SKIPPED
> Task :downloadServer SKIPPED
> Task :splitServerJar SKIPPED
> Task :mergeJars SKIPPED
> Task :applyBinaryPatches FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':applyBinaryPatches'.
> java/util/jar/Pack200

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':applyBinaryPatches'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
	at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.NoClassDefFoundError: java/util/jar/Pack200
	at net.minecraftforge.gradle.user.patcherUser.TaskApplyBinPatches.setup(TaskApplyBinPatches.java:202)
	at net.minecraftforge.gradle.user.patcherUser.TaskApplyBinPatches.doTask(TaskApplyBinPatches.java:80)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
	... 31 more
Caused by: java.lang.ClassNotFoundException: java.util.jar.Pack200
	... 50 more

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
5 actionable tasks: 5 executed

Minecraft process finished unexpectedly. There was an error with Malmo.****

**Comment by Laz9999** [comment]
For Deprecated Gradle feature --> Go to Malmo project download latest prebuild version https://github.com/Microsoft/malmo/releases. Then find and replace the Malmo directory in your python package directory @ xxx/minedojo/sim/Malmo on your computer. (Reminder directory shall keep the same name "Malmo")

**Comment by Veitaserum4** [comment]
> For Deprecated Gradle feature --> Go to Malmo project download latest prebuild version https://github.com/Microsoft/malmo/releases. Then find and replace the Malmo directory in your python package directory @ xxx/minedojo/sim/Malmo on your computer. (Reminder directory shall keep the same name "Malmo")
