### ISSUE TITLE
Strange error in minedojo and mineclip

### ISSUE THREAD

**Issue by tonymacx86PRO** [MineDojo/MineDojo#89]
```
Successfully installed gym-0.19.0
(steve) coder@TONY-PC:~/STEVE-1$ . run_agent/3_run_interactive_session.sh
Traceback (most recent call last):
  File "/home/coder/STEVE-1/steve1/run_agent/run_interactive.py", line 9, in <module>
    from steve1.utils.mineclip_agent_env_utils import load_mineclip_agent_env
  File "/home/coder/STEVE-1/steve1/utils/mineclip_agent_env_utils.py", line 9, in <module>
    from steve1.mineclip_code.load_mineclip import load
  File "/home/coder/STEVE-1/steve1/mineclip_code/load_mineclip.py", line 2, in <module>
    from mineclip import MineCLIP
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/mineclip/__init__.py", line 2, in <module>
    from .dense_reward import (
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/mineclip/dense_reward/__init__.py", line 1, in <module>
    from .animal_zoo import AnimalZooDenseRewardWrapper, HuntCowDenseRewardEnv
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/mineclip/dense_reward/animal_zoo/__init__.py", line 2, in <module>
    from .hunt_cow import HuntCowDenseRewardEnv
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/mineclip/dense_reward/animal_zoo/hunt_cow.py", line 4, in <module>
    import minedojo
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minedojo/__init__.py", line 1, in <module>
    from .tasks import make
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minedojo/tasks/__init__.py", line 83, in <module>
    _ALL_TASKS_SPECS_UNFILLED = OmegaConf.load(_resource_file_path("tasks_specs.yaml"))
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minedojo/tasks/__init__.py", line 29, in _resource_file_path
    with importlib_resources.path("minedojo.tasks.description_files", fname) as p:
AttributeError: module 'importlib_resources' has no attribute 'path'
```

**Comment by astelmach01** [comment]
change the import to `import importlib.resources as resources`

change `with importlib_resources.path()` to:`with resources.path()`
